using System.Text.Json.Serialization;
using OutSystems.ExternalLibraries.SDK;

namespace Without.Systems.BedrockRuntime.Structures;

[OSStructure(
    Description = "Response structure for Anthropic Claude 3 Models")]
public struct AnthropicClaude3TextResponse
{
    [OSStructureField(
        Description = "The unique identifier for the response",
        DataType = OSDataType.Text)]
    public string Id;

    [OSStructureField(
        Description = "The ID for the Anthropic Claude model that made the request",
        DataType = OSDataType.Text)]
    public string Model;

    [OSStructureField(
        Description = "The type of the response. The value is always message",
        DataType = OSDataType.Text)]
    public string Type;
    
    [OSStructureField(
        Description = "The conversational role of the generated message. The value is always assistant.",
        DataType = OSDataType.Text)]
    public string Role;
    
    [OSStructureField(
        Description = "The reason why Anthropic Claude stopped generating the response.  end_turn – The model reached a natural stopping point  max_tokens – The generated text exceeded the value of the max_tokens input field or exceeded the maximum number of tokens that the model supports.' .  stop_sequence – The model generated one of the stop sequences that you specified in the stop_sequences input field.",
        DataType = OSDataType.Text)]
    public string StopReason;
    
    [OSStructureField(
        Description = "Stop sequence",
        DataType = OSDataType.Text)]
    public string StopSequence;

    [OSStructureField(
        Description = "The content generated by the model. Returned as an array.",
        DataType = OSDataType.InferredFromDotNetType)]
    public List<AnthropicClaude3ContentResponseItem> Content;

    [OSStructureField(
        Description =
            "Container for the number of tokens that you supplied in the request and the number tokens of that the model generated in the response.",
        DataType = OSDataType.InferredFromDotNetType)]
    public AnthropicClaude3Usage Usage;

}

[OSStructure(Description = "Content of Anthropic Claude 3 models")]
public struct AnthropicClaude3ContentResponseItem
{
    [OSStructureField(
        Description = "The type of the content. Currently the only supported value is text",
        DataType = OSDataType.Text)]
    public string Type;
    
    [OSStructureField(
        Description = "The text of the content",
        DataType = OSDataType.Text)]
    public string Text;
}

[OSStructure(Description = "Anthropic Claude 3 Usage")]
public struct AnthropicClaude3Usage
{
    [OSStructureField(
        Description = "The number of tokens used in the request",
        DataType = OSDataType.Integer)]
    public int InputTokens;

    [OSStructureField(
        Description = "The number tokens of that the model generated in the response",
        DataType = OSDataType.Integer)]
    public int OutputTokens;
}