using OutSystems.ExternalLibraries.SDK;

namespace Without.Systems.BedrockRuntime.Structures;

[OSStructure(Description = "The details for the guardrails contextual grounding filter.")]
public struct GuardrailContextualGroundingFilter
{
    [OSStructureField(Description = "The action performed by the guardrails contextual grounding filter",
        DataType = OSDataType.Text,
        IsMandatory = true)]
    public string Action;
    
    [OSStructureField(Description = "The score generated by contextual grounding filter",
        DataType = OSDataType.Decimal,
        IsMandatory = true)]
    public double Score;
    
    [OSStructureField(Description = "The threshold used by contextual grounding filter to determine whether the content is grounded or not",
        DataType = OSDataType.Decimal,
        IsMandatory = true)]
    public double Threshold;
    
    [OSStructureField(Description = "The contextual grounding filter type",
        DataType = OSDataType.Text,
        IsMandatory = true)]
    public string Type;
}